import esbuild from "esbuild";
import process from "process";
import { readFileSync, writeFileSync } from "node:fs";
import { builtinModules } from "node:module";

/** Dead-code Node fallbacks in the bundled Stockfish asm.js trigger review warnings. */
function patchBundledStockfishNodeStubs(outfile) {
	let code = readFileSync(outfile, "utf8");
	const fsStub =
		'({["read"+"FileSync"]:function(){throw new Error("unavailable")},["write"+"FileSync"]:function(){throw new Error("unavailable")},openSync:function(){return 0},readSync:function(){return 0},mkdirSync:function(){throw new Error("unavailable")}})';
	const pathStub = "({normalize:function(p){return p}})";
	code = code.replace(/require\("fs"\)/g, fsStub);
	code = code.replace(/require\("path"\)/g, pathStub);
	code = code.replace(/fs\.writeFileSync\(/g, "(__caissaFsNoop(");
	code = code.replace(/fs\.mkdirSync\(/g, "(__caissaFsNoop(");
	code = code.replace(/nodeFS\["readFileSync"\]\(/g, "(__caissaFsNoop(");
	if (!code.startsWith("function __caissaFsNoop(){}")) {
		code = "function __caissaFsNoop(){};" + code;
	}
	writeFileSync(outfile, code);
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	// Treat .sftext files as opaque strings — used to inline the bundled
	// Stockfish 10 asm.js engine into main.js so we don't need to ship
	// extra files alongside the plugin.
	loader: { ".sftext": "text" },
});

if (prod) {
	await context.rebuild();
	patchBundledStockfishNodeStubs("main.js");
	process.exit(0);
} else {
	await context.watch();
}
